In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
indep=SC.fit_transform(indep)

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {
    'criterion': ['poisson', 'squared_error', 'friedman_mse', 'absolute_error'],
    'splitter': ['random', 'best'],
    'max_features': [None, 'sqrt', 'log2']}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose=3,n_jobs=-1)
regressor=grid.fit(indep,dep)
y_pred=regressor.predict(indep)
y_pred

Fitting 5 folds for each of 24 candidates, totalling 120 fits

array([16884.924 ,  1725.5523,  4449.462 , ...,  1629.8335,  2007.945 ,
       29141.3603])

In [9]:
from sklearn.metrics import r2_score
r_score=r2_score(dep,y_pred)
r_score

0.998667156135576

In [10]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'poisson', 'max_features': None, 'splitter': 'best'}:

In [11]:
table=pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008577,0.003133,0.002430,0.002255,poisson,None,random,"{'criterion': 'poisson', 'max_features': None,...",0.699136,0.563067,0.704595,0.693111,0.694084,0.670799,0.054021,11
1,0.010583,0.002516,0.001600,0.000994,poisson,None,best,"{'criterion': 'poisson', 'max_features': None,...",0.740656,0.660119,0.766234,0.736776,0.701817,0.721120,0.036758,1
2,0.002324,0.003001,0.006865,0.004141,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.688857,0.617165,0.723608,0.638047,0.559755,0.645486,0.056906,18
3,0.008087,0.001874,0.000811,0.001622,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.694136,0.587857,0.289817,0.751359,0.716335,0.607901,0.168139,23
4,0.009065,0.001807,0.001079,0.001322,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.649792,0.677655,0.664380,0.667496,0.674889,0.666842,0.009786,14
5,0.006853,0.003738,0.001407,0.002815,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.672774,0.531950,0.700800,0.675187,0.711554,0.658453,0.064964,17
6,0.006339,0.001582,0.000000,0.000000,squared_error,None,random,"{'criterion': 'squared_error', 'max_features':...",0.695103,0.614745,0.700040,0.728361,0.708989,0.689447,0.039041,6
7,0.008684,0.002439,0.000202,0.000403,squared_error,None,best,"{'criterion': 'squared_error', 'max_features':...",0.735635,0.658737,0.742996,0.724848,0.681467,0.708737,0.032865,3
8,0.006124,0.001877,0.001685,0.001773,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.731523,0.529259,0.617781,0.674702,0.486601,0.607973,0.090267,22
9,0.005280,0.002534,0.002282,0.001563,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.756182,0.450965,0.761558,0.688223,0.666715,0.664729,0.113129,15
10,0.003497,0.003922,0.002616,0.003582,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.656486,0.637785,0.728925,0.651302,0.677142,0.670328,0.031914,12
11,0.006580,0.005267,0.002144,0.003523,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.579221,0.631574,0.706756,0.712386,0.712039,0.668395,0.054073,13
12,0.004555,0.003530,0.001070,0.001424,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.682896,0.578423,0.675718,0.709582,0.721125,0.673549,0.050404,9
13,0.009250,0.000673,0.001425,0.001176,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.722479,0.648393,0.740301,0.743240,0.693273,0.709537,0.035364,2
14,0.005380,0.004370,0.001416,0.002333,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.606137,0.579985,0.613905,0.748499,0.611441,0.631994,0.059492,20
15,0.005175,0.002140,0.000960,0.000862,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.682476,0.599712,0.700867,0.542960,0.484015,0.602006,0.082052,24
16,0.003735,0.002297,0.000842,0.001033,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.663562,0.678098,0.667838,0.691953,0.597697,0.659830,0.032570,16
17,0.005044,0.004297,0.001594,0.002711,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.746612,0.550203,0.630445,0.749397,0.721966,0.679725,0.077868,8
18,0.037987,0.003821,0.003369,0.003307,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.718630,0.564668,0.745152,0.766896,0.704188,0.699907,0.070983,5
19,0.036717,0.012260,0.002127,0.003515,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.751793,0.597992,0.719859,0.703657,0.760480,0.706756,0.058182,4
20,0.018901,0.002981,0.001102,0.002203,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.619115,0.514922,0.716938,0.645640,0.671688,0.633660,0.067580,19
21,0.028947,0.005629,0.000215,0.000430,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.690913,0.556743,0.518333,0.716779,0.634095,0.623373,0.075993,21
22,0.026503,0.006671,0.000955,0.001461,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.686672,0.597991,0.656022,0.759905,0.654991,0.671116,0.052840,10
23,0.025505,0.004559,0.000601,0.001203,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.717520,0.602746,0.616457,0.734024,0.739332,0.682016,0.059720,7

In [13]:
import pickle

In [14]:
filename="DT_grid.sav"
pickle.dump(regressor,open(filename,"wb"))

In [15]:
loaded_model=pickle.load(open("DT_grid.sav",'rb'))

In [39]:
age=float(input("Age:"))
bmi=float(input("BMI:"))
children=float(input("Children:"))
sex_male=int(input("Sex Male 0 or 1:"))
smoker=int(input("Smoker Yes 0 or 1:"))

Age: 25
BMI: 25
Children: 0
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 0

In [17]:
Preinput=SC.transform([[age,bmi,children,sex_male,smoker]])

C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [18]:
Preinput

array([[-1.01155712, -0.92904899, -0.07876719, -1.0105187 ,  1.97058663]])

In [19]:
Future_Prediction=loaded_model.predict(Preinput)
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[16577.7795]