In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
indep=SC.fit_transform(X_train)
X_test=SC.transform(X_test)

In [9]:
X_train

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]

In [10]:
X_test

array([[ 0.89459283, -0.08863026, -0.06746417,  1.02378711, -0.50466988],
       [ 0.53757957, -0.22180837, -0.06746417, -0.97676557, -0.50466988],
       [ 0.60898222,  1.57449152,  0.76341038,  1.02378711,  1.98149332],
       ...,
       [ 1.10880078,  1.20785059, -0.89833872,  1.02378711, -0.50466988],
       [ 1.75142463,  1.34905148, -0.06746417,  1.02378711, -0.50466988],
       [ 1.60861933, -0.92299913, -0.89833872, -0.97676557, -0.50466988]])

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {
    'criterion': ['poisson', 'squared_error', 'friedman_mse', 'absolute_error'],
    'splitter': ['random', 'best'],
    'max_features': [None, 'sqrt', 'log2']}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose=3,n_jobs=-1)
regressor=grid.fit(X_train,y_train)
y_pred=regressor.predict(X_test)
y_pred

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([ 1694.7964 ,  2196.4732 , 13747.87235,  1694.7964 ,  2196.4732 ,
        1694.7964 ,  2196.4732 ,  2201.0971 ,  2201.0971 ,  2304.0022 ,
        2201.0971 ,  2201.0971 ,  2196.4732 ,  2196.4732 , 13747.87235,
        2201.0971 ,  1694.7964 ,  1694.7964 ,  1711.0268 , 13747.87235,
       13747.87235,  2201.0971 ,  2196.4732 , 13747.87235,  1694.7964 ,
        1694.7964 ,  2196.4732 ,  2201.0971 ,  2196.4732 ,  1711.0268 ,
        2201.0971 , 13747.87235,  1694.7964 ,  1694.7964 , 13747.87235,
        2196.4732 ,  1711.0268 , 13747.87235, 13747.87235,  2196.4732 ,
        2196.4732 ,  1694.7964 , 13747.87235, 13747.87235, 13747.87235,
        2201.0971 ,  2201.0971 ,  1694.7964 ,  2196.4732 ,  2196.4732 ,
        2196.4732 ,  2201.0971 , 13747.87235, 12829.4551 ,  2196.4732 ,
        1694.7964 ,  1694.7964 ,  1694.7964 ,  4005.4225 ,  1694.7964 ,
        1694.7964 , 12829.4551 ,  2304.0022 ,  1711.0268 ,  2304.0022 ,
        2196.4732 , 13747.87235, 12829.4551 ,  2201.0971 ,  2304.0022 ,
        2196.4732 ,  1694.7964 , 13747.87235,  2196.4732 ,  2196.4732 ,
        2196.4732 ,  1694.7964 ,  1711.0268 , 13747.87235, 13747.87235,
        2196.4732 , 13747.87235,  1694.7964 ,  1694.7964 , 13747.87235,
       13747.87235,  2196.4732 ,  1694.7964 ,  1694.7964 , 13747.87235,
        2201.0971 ,  1694.7964 ,  2196.4732 ,  2201.0971 ,  1694.7964 ,
        2196.4732 , 13747.87235, 13747.87235,  2201.0971 ,  1694.7964 ,
        1694.7964 ,  1694.7964 ,  2201.0971 , 13747.87235, 12829.4551 ,
        2196.4732 ,  1694.7964 ,  2196.4732 ,  1694.7964 , 13747.87235,
        2201.0971 ,  1711.0268 ,  2196.4732 , 13747.87235, 13747.87235,
        1711.0268 ,  1694.7964 ,  1694.7964 ,  1694.7964 ,  2304.0022 ,
       12829.4551 ,  2196.4732 ,  2196.4732 ,  2304.0022 ,  2196.4732 ,
        2201.0971 , 13747.87235, 13747.87235, 13747.87235,  1694.7964 ,
        2201.0971 ,  1694.7964 ,  2196.4732 ,  1694.7964 , 13747.87235,
       13747.87235, 13747.87235,  2201.0971 , 13747.87235,  1694.7964 ,
        2196.4732 ,  1694.7964 ,  1711.0268 ,  1694.7964 ,  1694.7964 ,
        2196.4732 ,  2196.4732 ,  2201.0971 ,  1694.7964 ,  1694.7964 ,
        2196.4732 , 13747.87235,  1694.7964 ,  1694.7964 ,  2196.4732 ,
        2196.4732 ,  1694.7964 ,  1694.7964 ,  2201.0971 ,  2201.0971 ,
        2304.0022 ,  1694.7964 ,  2196.4732 ,  1694.7964 ,  2196.4732 ,
        2304.0022 , 13747.87235,  2201.0971 ,  1694.7964 ,  2196.4732 ,
        1711.0268 ,  1711.0268 ,  2201.0971 ,  1694.7964 ,  2304.0022 ,
        2304.0022 ,  1711.0268 ,  1694.7964 , 12829.4551 ,  1694.7964 ,
        2201.0971 ,  2304.0022 ,  1694.7964 ,  1694.7964 ,  1711.0268 ,
       13747.87235,  1694.7964 ,  2196.4732 ,  2196.4732 ,  2201.0971 ,
       13747.87235,  2201.0971 ,  2196.4732 , 13747.87235,  1694.7964 ,
        1694.7964 ,  1711.0268 ,  2201.0971 ,  1711.0268 ,  1694.7964 ,
        2196.4732 , 13747.87235,  2201.0971 , 12829.4551 ,  1711.0268 ,
       13747.87235,  1711.0268 ,  1694.7964 ,  2201.0971 ,  1694.7964 ,
        1694.7964 ,  2196.4732 ,  2201.0971 ,  2196.4732 ,  1694.7964 ,
        1694.7964 ,  2304.0022 ,  2196.4732 ,  2201.0971 ,  2201.0971 ,
        2201.0971 ,  2201.0971 ,  2196.4732 ,  2196.4732 ,  2196.4732 ,
        1694.7964 ,  2201.0971 ,  2196.4732 ,  2304.0022 ,  1694.7964 ,
        1694.7964 ,  1694.7964 ,  2196.4732 ,  2201.0971 ,  2196.4732 ,
        1711.0268 ,  2196.4732 , 13747.87235,  1694.7964 ,  2201.0971 ,
        2196.4732 , 12829.4551 ,  2201.0971 ,  2196.4732 ,  2304.0022 ,
        1694.7964 ,  1711.0268 ,  2196.4732 ,  2196.4732 ,  1694.7964 ,
       13747.87235, 13747.87235,  2201.0971 ,  2196.4732 ,  2196.4732 ,
        1694.7964 ,  1694.7964 ,  2196.4732 ,  2304.0022 ,  2196.4732 ,
        2304.0022 , 13747.87235, 13747.87235,  2201.0971 ,  1694.7964 ,
        1694.7964 , 12829.4551 ,  2304.0022 , 12829.4551 ,  1694.7964 ,
       13747.87235,  1711.0268 ,  2196.4732 ,  2201.0971 , 13747.87235,
        2196.4732 ,  1694.7964 ,  4005.4225 ,  1694.7964 ,  2196.4732 ,
        2196.4732 ,  1694.7964 ,  1694.7964 ,  2196.4732 ,  1694.7964 ,
        2304.0022 ,  4005.4225 , 13747.87235,  1694.7964 ,  1694.7964 ,
        1711.0268 , 13747.87235,  1694.7964 ,  2196.4732 ,  2201.0971 ,
        2196.4732 , 13747.87235,  2196.4732 ,  1694.7964 ,  1694.7964 ,
        1694.7964 ,  1711.0268 , 13747.87235, 13747.87235,  2196.4732 ,
        1694.7964 ,  2196.4732 ,  2304.0022 ,  1694.7964 , 13747.87235,
       12829.4551 ,  2201.0971 , 13747.87235,  2196.4732 ,  1694.7964 ,
        1694.7964 ,  2196.4732 ,  1711.0268 ,  1694.7964 , 13747.87235,
        2201.0971 ,  2196.4732 ,  2196.4732 ,  2196.4732 ,  2196.4732 ,
        2196.4732 , 13747.87235, 13747.87235,  1694.7964 , 13747.87235,
        2201.0971 ,  1711.0268 ,  1694.7964 ,  2304.0022 , 13747.87235,
        2196.4732 ,  2196.4732 ,  1694.7964 , 13747.87235,  2196.4732 ,
       12829.4551 ,  2196.4732 ,  1694.7964 , 13747.87235,  2201.0971 ,
        2196.4732 , 12829.4551 ,  1694.7964 ,  2304.0022 ,  1711.0268 ,
        4005.4225 ,  2196.4732 ,  1711.0268 ,  2304.0022 , 13747.87235,
        2196.4732 , 13747.87235, 13747.87235,  1694.7964 ,  4005.4225 ,
        1694.7964 ,  2196.4732 ,  2201.0971 ,  1694.7964 , 13747.87235,
        1694.7964 ,  2196.4732 ,  1694.7964 ,  2196.4732 ,  2196.4732 ,
        1694.7964 ,  1694.7964 ,  1694.7964 , 13747.87235,  1711.0268 ,
        2196.4732 , 13747.87235,  1694.7964 , 13747.87235,  1694.7964 ,
        1694.7964 ,  1694.7964 ,  2196.4732 ,  2201.0971 ,  1694.7964 ,
        2196.4732 ,  2196.4732 ,  2201.0971 ,  1694.7964 ,  2201.0971 ,
        2196.4732 , 13747.87235,  1694.7964 ,  2196.4732 ,  2196.4732 ,
        2196.4732 ,  1694.7964 ,  1694.7964 , 12829.4551 ,  1694.7964 ,
        1694.7964 ,  2196.4732 ])

In [12]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

-0.021961939812008557

In [13]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': None, 'splitter': 'best'}:

In [14]:
table=pd.DataFrame.from_dict(re)

In [15]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.012686,0.004818,0.005584,0.001989,poisson,None,random,"{'criterion': 'poisson', 'max_features': None,...",0.654284,0.662002,0.663943,0.613136,0.632116,0.645096,0.019572,8
1,0.009893,0.001893,0.003402,0.003364,poisson,None,best,"{'criterion': 'poisson', 'max_features': None,...",0.698645,0.613867,0.686651,0.582830,0.610067,0.638412,0.045717,10
2,0.011961,0.002437,0.002116,0.003527,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.723115,0.571849,0.655109,0.576998,0.610753,0.627565,0.056271,13
3,0.010411,0.002278,0.000466,0.000933,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.692963,0.618387,0.657990,0.309447,0.671929,0.590143,0.142445,16
4,0.006053,0.003288,0.006059,0.004644,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.688095,0.631920,0.592814,0.425280,0.633679,0.594357,0.089815,15
5,0.010116,0.003842,0.005099,0.001251,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.657537,0.704076,0.613426,0.278758,0.443070,0.539374,0.157333,23
6,0.005971,0.002196,0.004593,0.003935,squared_error,None,random,"{'criterion': 'squared_error', 'max_features':...",0.706568,0.679884,0.649853,0.646994,0.664450,0.669550,0.021908,2
7,0.007967,0.004709,0.004834,0.005920,squared_error,None,best,"{'criterion': 'squared_error', 'max_features':...",0.715076,0.543206,0.748097,0.624448,0.689050,0.663975,0.072752,3
8,0.006010,0.004811,0.006286,0.005915,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.695205,0.592041,0.542084,0.388494,0.655053,0.574575,0.106785,18
9,0.009163,0.001184,0.002697,0.002591,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.358204,0.693642,0.371554,0.587551,0.696162,0.541423,0.149444,21
10,0.007494,0.002538,0.002800,0.000579,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.515759,0.588300,0.497192,0.310063,0.558799,0.494023,0.097374,24
11,0.006346,0.000590,0.003187,0.001097,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.776321,0.583431,0.690973,0.701282,0.556589,0.661719,0.080915,4
12,0.005406,0.001642,0.003755,0.002788,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.667583,0.645375,0.650480,0.660245,0.642903,0.653317,0.009285,5
13,0.008704,0.001757,0.004128,0.000698,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.751751,0.582160,0.777061,0.612490,0.664015,0.677495,0.076057,1
14,0.004996,0.001169,0.003479,0.000918,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.680830,0.586218,0.555803,0.600547,0.488277,0.582335,0.062608,17
15,0.006398,0.001683,0.004373,0.001549,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.697949,0.679912,0.637416,0.464417,0.608938,0.617726,0.082791,14
16,0.006427,0.000793,0.002820,0.001269,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.685440,0.514063,0.451251,0.639883,0.581740,0.574475,0.084235,19
17,0.005432,0.001909,0.007002,0.004744,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.595368,0.394911,0.685176,0.587957,0.532928,0.559268,0.095589,20
18,0.025477,0.002926,0.002783,0.002468,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.695500,0.649602,0.660907,0.594659,0.665011,0.653136,0.032949,6
19,0.032559,0.003039,0.003059,0.002541,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.740450,0.606841,0.615472,0.547972,0.660347,0.634216,0.064042,11
20,0.019162,0.002691,0.001073,0.001748,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.709586,0.584686,0.718727,0.538975,0.601355,0.630666,0.071223,12
21,0.019708,0.003259,0.003053,0.003152,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.793586,0.594832,0.567979,0.640556,0.639370,0.647265,0.078170,7
22,0.017444,0.001703,0.001807,0.001846,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.769820,0.562054,0.630799,0.614877,0.621373,0.639785,0.069270,9
23,0.020154,0.004872,0.001055,0.001306,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.782355,0.527685,0.587260,0.378336,0.429840,0.541095,0.140986,22