In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
X_train=SC.fit_transform(X_train)
X_test=SC.transform(X_test)

In [9]:
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]])

In [10]:
X_test

array([[ 0.89459283, -0.08863026, -0.06746417,  1.02378711, -0.50466988],
       [ 0.53757957, -0.22180837, -0.06746417, -0.97676557, -0.50466988],
       [ 0.60898222,  1.57449152,  0.76341038,  1.02378711,  1.98149332],
       ...,
       [ 1.10880078,  1.20785059, -0.89833872,  1.02378711, -0.50466988],
       [ 1.75142463,  1.34905148, -0.06746417,  1.02378711, -0.50466988],
       [ 1.60861933, -0.92299913, -0.89833872, -0.97676557, -0.50466988]])

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
param_grid = {
    'fit_intercept': [True, False],
    'copy_X': [True, False],
    'n_jobs': [1, -1],
    'positive': [False, True]}
grid = GridSearchCV(LinearRegression(),param_grid, refit=True, verbose=3, n_jobs=-1)
regressor=grid.fit(X_train,y_train)
y_pred=regressor.predict(X_test)
y_pred

Fitting 5 folds for each of 16 candidates, totalling 80 fits

array([11494.66343731,  9939.13858872, 37674.80720199, 15971.18826784,
        6867.78163959,  3551.94938018,  1012.29574839, 14160.72797496,
        8827.05979112,  7296.70496722,  4197.7766988 , 10170.95536354,
        9077.94710705,  4236.14697304, 27449.33042523, 11262.99180505,
       11200.63995584,  5526.20791971,  8052.77553825, 26345.85480423,
       33386.71543976, 14157.21695329, 11241.94212032, 32390.79221085,
        4436.36725655,  8628.219732  ,   693.86854098, 10238.19385142,
        4179.47173701, 10253.94053816,  8854.84846455, 40226.06811219,
       15914.47100708, 14077.59765777, 24114.57927836,  4624.55278387,
       12975.14771438, 30712.12454447, 33111.91224936,  3769.86458779,
        3579.73805361,  4369.93709213, 29872.42396689, 39094.38817786,
       27808.93372292,  4767.43465047, 11157.07440884,  7669.47372023,
        3172.96690729, 10787.40754866,  5045.64574469,  3196.58598555,
       33172.5515643 , 37789.47291737, 16330.70751607,  6517.72052354,
        5997.25547683,  9293.19703379,  9549.61653975, 11670.01049236,
        2035.61496717, 38643.61216886, 15430.00584627, 12122.40314828,
       13612.69160896, 14221.7829298 , 25948.41110851, 31779.20831545,
        1304.25675619, 10025.5205487 , 12703.79707564, 12058.41630319,
       25259.39908856, 15995.7673232 , 11109.16584094, 12237.34659148,
        6942.74276904, 10058.70278066, 29551.72153907, 39188.26358737,
       11602.43318354, 37255.55936069,  3903.57065743,  9689.88626867,
       34117.3191899 , 29165.77088545,  8706.9394241 ,  4599.46680865,
       12432.84372785, 30405.3466402 ,  9505.97806175, 11702.4802882 ,
        7634.70963558,  9398.5773233 ,  7820.74140928,  6768.24606218,
       35369.74064742, 33316.73683633,  7376.17912016, 15298.30838768,
        4305.82878025,  8531.34022067,  6674.91959725, 31673.06172721,
       32663.83893857,  1777.66358318,  9456.80350575,  6304.28092208,
       14069.53158788, 37337.70141761, 10147.05855746, 10791.76168803,
       10039.69261324, 26165.60927262, 40028.16968121,  8077.86151347,
         612.36670861,  9354.17977707, 15514.07707217,  9456.56780265,
       35380.23168769,  7217.08106431, 17168.3337821 ,  9081.80155705,
        8565.46408078,  2835.66744454, 32312.92286694, 31229.9361482 ,
       39616.53024518,  5170.31392945,  9776.25639076,  3874.43655384,
        8042.38038532,  8270.38473487, 31798.15278236, 29992.31974928,
       30077.79749845,  9310.77772159, 32818.35366303,  3106.19792193,
        3326.93729455, 10978.71141409, 13536.78885137, 12367.42017266,
        5271.46615379, 15971.14624311, 15327.91922428,  2233.94810644,
        -193.46478035, 10488.95509316,  6943.08619737, 31824.03985054,
       11910.85792157,  2674.03939679,  6008.28362381,  8275.58461503,
        4129.01022085,  2462.20460437, 11250.15333278, 12336.65107319,
        6753.26567418, 16726.50437803, 11688.50190203, 14285.97529114,
        2761.87641584,  6784.56536927, 23204.18766124,  7113.7567374 ,
        5016.34354219,  5346.88494786,  6466.84336748,  4742.72952092,
        9799.27266182,  5622.82805217,  6019.86794587,  7052.01953328,
        3309.63505401,  5462.9033239 , 37534.73115144,   951.31300512,
       12455.10553807,  8782.67408277, 13537.28393334,  5690.18800684,
        4826.0955412 , 35893.88020732,  3781.60517089,  2282.42396789,
       15006.65601398, 12199.98292647, 34446.51055803,  5170.70661301,
        5989.32271162, 31554.13775981,  5805.2273374 ,  2393.95227677,
        7977.89845826,  9489.38102683,  8309.6710578 ,  5565.18823164,
       12684.33385098, 38715.64140807, 13563.98655548, 29054.24257657,
        6525.12341255, 35684.62664631,  3328.93478714, 12277.04394692,
        9397.64753305,  6370.75311123, 11137.38199215, 14094.6175631 ,
        4998.66045598,  4575.43669788,  8209.23850007,  1623.64394069,
        7457.65076569,  4007.42557998, 13477.50219709,  3953.03740225,
       10296.05102609,  6859.01497147,  9576.74131286,  1902.33176793,
       13503.03399905, 16592.20733907, 15341.56602001, 10967.43572613,
        5909.51696823,  2632.51987818,  2239.97465902, 12908.58424527,
       14434.87910293,  4505.82059117,  4235.85740732,  9769.87917936,
        9551.83066706, 27499.12153   ,  7187.01717046, 10151.65563041,
        6581.2378661 , 29339.51773886, 11342.59203219,  7061.54066225,
       10085.69496851, 12060.61208154,  2541.56452101, 10580.0483624 ,
        1037.38172361,  6649.36411951, 28653.66147436, 38857.34133603,
        6544.42314568,  8362.45442649,  1927.03689748,   -54.90225888,
       10813.25259212,  4393.62838197,  4816.52054962,  2805.50766335,
        7467.15354571, 33559.81746123, 37601.39701896, 14636.97080485,
        8082.45858642, 15549.71446135, 33017.06502486,  9151.65408629,
       33702.45178685,  3616.90080975, 29979.02821977,  8412.33681121,
       13746.12646184,  3908.27084823, 32389.57285488,  7832.74137124,
       11652.2242883 ,  9676.90337326,  3948.76468924, 13075.8232057 ,
       11599.73048533,  8186.63786892, 12908.15676748,  2231.95061385,
       10083.69747592,  5758.87504273, 11342.77919949, 31007.19928299,
       10032.51168577,   737.87340366,   379.37983303, 39215.54534094,
        9321.79403068,  6876.31721201, 13807.91752858, 12972.65053243,
       27348.81842544,  7502.06666089,  7207.92171263, 12435.41312138,
        2642.23278183,  4012.11854028, 24501.77296372, 26245.72365011,
       13513.67669297,  2786.58154539,  5184.93254016,  9762.03046361,
       12004.22641123, 22933.52387916, 30493.97363376, 10327.09134231,
       23693.10547186,  2611.7414102 , 11619.24034211,  7671.49416916,
        7848.91092838,   495.47502803,  7366.45437861, 35186.41157193,
        5635.087393  ,  5753.54185788,    50.46619274, 10998.60211654,
        6806.03720498, 10187.49853585, 39159.33500004, 27393.04787276,
       11090.29358559, 35581.67132718, 14567.49912128,  6647.08889909,
       11182.27462036,  7171.1069922 , 36398.33918843,  6142.37053912,
       10726.67234638,  1189.04209622, 24335.02908526,  1763.76924647,
       34727.45525673, 11396.72083104,  1705.4892014 , 31461.10546799,
        6985.9209593 ,  5616.24071711, 38079.26833366,  2581.25003856,
        9201.44519106,  2513.77584758, 13144.30472533,  1453.2025927 ,
       11152.25275125,  7200.96536979, 35951.77940672,  7618.874292  ,
       30272.32281984, 29556.74608981,  7265.6528131 , 10356.32856374,
        1757.98300438,  2621.7931348 ,  3580.97385486, 12539.98508743,
       37182.04677925, 10228.16770628,   751.76774038, 11064.78013258,
        4804.41746981, 10151.30497159,  5171.50309858,  7306.82167289,
        4454.19548534, 28100.46002243,  4058.40585388,  -761.01823362,
       33247.59674321, 13060.91502927, 36147.53592196, 10357.6082934 ,
        7500.03898145,  -137.8874335 ,  2381.70477382, 11897.72988359,
        6116.65156985,  2811.28667494, 11680.82128519,  8117.73419832,
        7387.86584063,  4989.36319222,  2880.75835851, 32146.49222997,
        3371.3230029 ,  9033.21797037,  4817.29796681, 12487.11043878,
       15073.63512299,  7521.49246821, 26881.16765369, 14392.14022834,
       17464.38494299, 11934.54460401])

In [12]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.7894429387120754

In [13]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'copy_X': True, 'fit_intercept': True, 'n_jobs': 1, 'positive': True}:

In [14]:
table=pd.DataFrame.from_dict(re)

In [15]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_copy_X,param_fit_intercept,param_n_jobs,param_positive,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.032928,0.006369,0.003844,0.002585,True,True,1,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,5
1,0.013989,0.011435,0.002665,0.002715,True,True,1,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
2,0.004633,0.001752,0.000707,0.001415,True,True,-1,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,5
3,0.005491,0.004126,0.001522,0.003043,True,True,-1,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
4,0.002036,0.002520,0.002666,0.003518,True,False,1,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",-0.698095,-0.586805,-0.459207,-0.600488,-0.419146,-0.552748,0.101157,13
5,0.003716,0.004000,0.001949,0.002496,True,False,1,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",-0.698095,-0.586653,-0.459207,-0.598656,-0.416113,-0.551745,0.101781,9
6,0.002529,0.003876,0.000237,0.000474,True,False,-1,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",-0.698095,-0.586805,-0.459207,-0.600488,-0.419146,-0.552748,0.101157,13
7,0.006298,0.005132,0.000000,0.000000,True,False,-1,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",-0.698095,-0.586653,-0.459207,-0.598656,-0.416113,-0.551745,0.101781,9
8,0.003853,0.002473,0.001404,0.002335,False,True,1,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,5
9,0.004100,0.002476,0.002138,0.002751,False,True,1,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
10,0.003223,0.002808,0.003838,0.002331,False,True,-1,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,5
11,0.004028,0.003956,0.000604,0.001209,False,True,-1,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
12,0.004677,0.004345,0.000000,0.000000,False,False,1,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",-0.698095,-0.586805,-0.459207,-0.600488,-0.419146,-0.552748,0.101157,13
13,0.003524,0.002324,0.001319,0.002639,False,False,1,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",-0.698095,-0.586653,-0.459207,-0.598656,-0.416113,-0.551745,0.101781,9
14,0.002223,0.002840,0.002386,0.002614,False,False,-1,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",-0.698095,-0.586805,-0.459207,-0.600488,-0.419146,-0.552748,0.101157,13
15,0.003113,0.002264,0.002641,0.002311,False,False,-1,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",-0.698095,-0.586653,-0.459207,-0.598656,-0.416113,-0.551745,0.101781,9