In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
X_train=SC.fit_transform(X_train)
X_test=SC.transform(X_test)

In [9]:
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]])

In [10]:
X_test

array([[ 0.89459283, -0.08863026, -0.06746417,  1.02378711, -0.50466988],
       [ 0.53757957, -0.22180837, -0.06746417, -0.97676557, -0.50466988],
       [ 0.60898222,  1.57449152,  0.76341038,  1.02378711,  1.98149332],
       ...,
       [ 1.10880078,  1.20785059, -0.89833872,  1.02378711, -0.50466988],
       [ 1.75142463,  1.34905148, -0.06746417,  1.02378711, -0.50466988],
       [ 1.60861933, -0.92299913, -0.89833872, -0.97676557, -0.50466988]])

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {'criterion':['squared_error','friedman_mse','absolute_error','poisson'],'max_features': [None,'sqrt','log2'],'n_estimators':[50,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose=3,n_jobs=-1)
regressor=grid.fit(X_train,y_train)
y_pred=regressor.predict(X_test)
y_pred

Fitting 5 folds for each of 24 candidates, totalling 120 fits

array([ 9843.326844  ,  9272.1685728 , 43613.011643  , 13882.99687   ,
        9441.088714  , 10424.245436  ,  1855.589988  , 12555.5771346 ,
        7928.4401398 ,  5665.928356  ,  6400.6223216 , 12792.9102356 ,
        8177.436699  ,  7914.5057002 , 25599.9055082 , 12535.8542002 ,
       13108.8750634 ,  5019.7230212 ,  7221.2236584 , 32419.543828  ,
       24336.872608  , 18828.2285778 ,  9954.0243556 , 31368.9243054 ,
        4228.2573888 ,  6349.8474922 ,  3380.32664   ,  8804.1980722 ,
        3661.389327  , 11106.4277074 ,  7587.4905642 , 44083.536745  ,
       15094.1454472 , 14376.3946996 , 19470.0576592 ,  4332.087402  ,
        9509.3152138 , 36503.824628  , 39478.2351818 ,  2447.364816  ,
        5865.9762742 ,  3157.91837   , 20581.9844312 , 46403.6827876 ,
       36818.515247  ,  3461.654014  , 12821.4576372 ,  6735.64542   ,
        7407.0462    , 13027.934722  ,  4302.229191  ,  4741.2097036 ,
       28324.4250378 , 44859.5773348 , 11633.797852  ,  9857.1443856 ,
        5442.0373536 , 12388.8185796 , 10257.967406  , 14300.5297082 ,
        2994.9697938 , 44750.1660372 , 16109.6205818 , 18811.4405658 ,
       11519.3611152 ,  9852.016408  , 30532.2005866 , 39119.1075718 ,
        4171.1474736 , 10825.3727204 , 15274.0470336 , 11612.7527268 ,
       16890.5673348 , 15180.3550828 , 13980.9897412 , 14456.7134154 ,
        9648.8327236 , 15184.119741  , 20474.094851  , 44590.9866288 ,
       11516.310175  , 44649.20463   ,  4029.842083  ,  8725.049698  ,
       37864.9869508 , 20550.3127364 ,  4685.464988  ,  3213.9900164 ,
       12993.4258204 , 38221.9989528 ,  5932.904016  , 15094.920562  ,
        3669.0492068 , 10959.193597  , 10059.2336352 ,  4633.997213  ,
       42851.829415  , 38475.604167  ,  5500.492351  , 10886.494243  ,
        4700.3304806 ,  9623.8742888 ,  7496.4490554 , 36102.6064936 ,
       25090.3657678 ,  3715.4269768 , 11324.199069  ,  3710.7933392 ,
       12001.2507166 , 44265.372882  , 11587.162483  ,  5757.2359968 ,
        9886.8811098 , 33901.2322716 , 44662.908844  ,  7950.3435994 ,
        1945.079421  , 12326.5545836 , 16333.158894  , 10775.6119692 ,
       40384.2240582 , 11628.8392774 , 15067.5033462 ,  7538.5082004 ,
       13300.552082  ,  5512.1076378 , 25337.0261216 , 24855.6681796 ,
       46066.396575  ,  1920.1621966 , 11450.4264112 ,  2859.8309298 ,
        7739.5843936 ,  9421.0860022 , 34574.7874714 , 35757.4048406 ,
       25291.6206192 , 11886.521307  , 24755.3114532 ,  4638.0889276 ,
        1959.189688  , 13055.6940836 ,  9570.5771742 , 10705.4922078 ,
        5906.4421022 , 15515.79663   , 20508.4648654 , 11210.906303  ,
        1590.075538  , 11055.4157718 ,  7264.4611396 , 39039.5146706 ,
        9143.340421  ,  5733.7332334 ,  4647.486102  ,  7972.0737422 ,
        3306.162966  ,  5514.569869  , 12535.8542002 , 10138.3305202 ,
        5527.6711106 , 13291.336641  , 14137.766061  ,  9205.347844  ,
        3664.210159  ,  7223.8862338 , 17181.7579192 ,  9252.4132006 ,
        5878.9691    ,  2268.03719133,  7578.210389  ,  6686.8379296 ,
        9386.6595128 ,  3897.7218898 ,  6601.3672904 ,  7530.1721652 ,
        4583.396512  ,  6377.9539088 , 30407.5067534 ,  2177.6045836 ,
       15334.7326544 ,  6735.102497  , 11686.8244798 ,  8424.1769022 ,
        8064.278097  , 28623.011058  ,  4251.9398764 ,  3312.6471922 ,
       15000.616563  , 10423.9276672 , 42236.2336074 ,  8797.6416586 ,
        5657.880576  , 27892.0310748 ,  5007.259007  ,  2804.2988438 ,
        9275.0069094 ,  6105.777251  ,  9554.3704408 ,  4486.467462  ,
       11358.3214254 , 45295.3955102 , 16685.4543126 , 20062.4246044 ,
       11587.2335592 , 40949.3648046 ,  4177.1375284 ,  9963.1085348 ,
       10262.134639  ,  1756.9153    ,  8685.218     , 13732.02459   ,
        6843.5421928 ,  4778.476559  ,  6610.1089232 ,  4060.3310478 ,
        7194.1696918 ,  6962.368555  , 14126.6397664 ,  7403.6852976 ,
       12052.7790622 ,  7878.818185  , 10599.5804866 ,  7682.96153   ,
       13401.7143022 , 14934.032378  , 17856.1287776 , 12337.2915016 ,
        7072.5537338 ,  2860.82252   ,  4664.5704256 ,  8059.676367  ,
       15728.2220974 ,  8951.797661  ,  7226.1992002 ,  7545.7165612 ,
       14545.9585384 , 33617.337999  ,  5702.105443  , 12240.9297604 ,
        6947.4552096 , 38435.938497  , 10289.5209114 ,  8344.684492  ,
       12630.4681588 , 10904.2552392 ,  2950.4155304 ,  8770.4241562 ,
        5108.5921468 ,  6747.7603084 , 20160.8153866 , 44640.006005  ,
        6765.2908994 ,  4685.982507  ,  5553.9064506 ,  1611.606058  ,
        8497.82335   ,  3878.76059542,  5657.2795506 ,  9808.615857  ,
        8623.573229  , 26519.2505458 , 45233.2876338 , 15767.4617196 ,
        6131.096286  , 11070.25052   , 41991.3044864 , 10664.2007412 ,
       39956.1583254 ,  1388.077659  , 37630.7961652 ,  6848.9471432 ,
       13490.5558446 ,  9188.3595446 , 38234.6184958 ,  5466.1175294 ,
       10339.1259366 , 10167.532822  ,  4270.0090596 , 14337.8104462 ,
       11554.313504  , 10870.5095936 , 13758.4818232 , 12462.295617  ,
        8081.0244048 ,  3700.741493  ,  9437.9709692 , 22589.5720944 ,
        4622.6491554 ,  1962.1297898 ,  2754.860209  , 45738.2716114 ,
       10418.0726028 ,  4393.098469  , 16921.762106  , 14080.7800204 ,
       33680.0148984 ,  8811.226728  ,  5616.1817824 ,  9444.5782044 ,
        5147.0933832 ,  3598.0174822 , 20538.773517  , 17329.7122106 ,
       13767.45834   ,  2819.537262  ,  3517.305527  , 10534.4869988 ,
       10490.6181396 , 17904.7727224 , 21566.366011  ,  7945.4208984 ,
       18263.5166974 ,  2540.7519592 ,  7811.5339482 ,  9954.043293  ,
       17120.9614924 ,  3007.5597456 ,  9466.985837  , 44785.336762  ,
        3961.6084758 ,  4890.4147472 ,  2541.8417968 , 14315.5875016 ,
        4856.113408  , 12074.850377  , 44950.1205156 , 18912.099676  ,
        9796.1063712 , 38762.3004392 , 19097.352     , 11307.1405582 ,
       10546.8144366 ,  5282.6664866 , 29848.37976   ,  4382.719644  ,
       14267.1260328 ,  2307.188079  , 17594.8958562 ,  3501.050717  ,
       24872.477989  ,  9407.3920944 ,  3558.267244  , 37182.743767  ,
        8434.6859298 ,  5271.466081  , 29242.0352814 ,  4730.1709656 ,
        9809.6141478 ,  3946.2611748 , 10866.5575078 ,  5127.38922   ,
        5769.0434442 ,  6817.7251424 , 43848.722234  , 10768.826767  ,
       33120.9866882 , 37724.590938  ,  5771.00601   ,  9485.873317  ,
        2731.1665532 ,  5029.5212076 ,  4296.1324608 ,  8972.1518208 ,
       46793.3285448 , 11404.802389  ,  2095.577673  , 12911.9158798 ,
        2180.741979  , 14082.0809198 ,  9267.944082  ,  2166.162788  ,
        5107.5293754 , 36169.548066  ,  6571.394603  ,  2349.4994018 ,
       40095.0992626 , 12640.3155498 , 44995.1756644 , 11880.16989   ,
        7598.8996034 ,  2448.546633  ,  2180.683301  , 12833.1418954 ,
        5586.3481562 ,  1762.628261  , 10245.8350058 ,  7169.302365  ,
        7494.3408816 , 10076.8148126 ,  9107.7907368 , 40436.0273818 ,
        3967.2731296 , 16367.6072068 ,  7170.86797412, 16437.481545  ,
       10798.703102  ,  8073.614126  , 18928.8573754 , 13054.8373424 ,
       18182.7971944 , 18893.710345  ])

In [12]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8655274694475142

In [13]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 50}:

In [14]:
table=pd.DataFrame.from_dict(re)

In [15]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.270003,0.013902,0.009447,0.001704,squared_error,None,50,"{'criterion': 'squared_error', 'max_features':...",0.864406,0.766150,0.820616,0.791947,0.771963,0.803017,0.036123,17
1,0.516415,0.006662,0.024681,0.008132,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",0.861384,0.763754,0.814765,0.801634,0.769833,0.802274,0.035176,20
2,0.208277,0.009289,0.010467,0.001950,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.852463,0.787433,0.807320,0.829434,0.774600,0.810250,0.028107,10
3,0.415381,0.016474,0.018472,0.002897,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.863451,0.791220,0.806248,0.828298,0.771083,0.812060,0.031787,5
4,0.216757,0.020188,0.009196,0.001306,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.871176,0.795963,0.808952,0.821441,0.765032,0.812513,0.034820,4
5,0.416817,0.013414,0.023695,0.009068,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.861025,0.795819,0.809698,0.835223,0.767676,0.813888,0.032114,2
6,0.279688,0.022244,0.006879,0.001439,friedman_mse,None,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.862035,0.761988,0.815176,0.789928,0.771238,0.800073,0.035923,22
7,0.555143,0.015352,0.018898,0.003883,friedman_mse,None,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.862594,0.770821,0.816140,0.796661,0.767207,0.802685,0.034872,18
8,0.218092,0.010440,0.018285,0.012228,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.852823,0.796009,0.789751,0.822379,0.762753,0.804743,0.030617,16
9,0.427558,0.009968,0.020527,0.007213,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.861913,0.788178,0.806825,0.828839,0.770816,0.811314,0.031821,7
10,0.224562,0.010912,0.010765,0.003546,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.864228,0.794183,0.812934,0.827668,0.775227,0.814848,0.030342,1
11,0.452716,0.019060,0.019753,0.002790,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.865726,0.790124,0.804634,0.821096,0.767672,0.809850,0.032997,12
12,1.266092,0.118508,0.016260,0.004121,absolute_error,None,50,"{'criterion': 'absolute_error', 'max_features'...",0.849526,0.783883,0.798847,0.796012,0.763617,0.798377,0.028427,23
13,3.156953,0.227535,0.030575,0.006041,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",0.849513,0.779506,0.799811,0.793860,0.763293,0.797197,0.029042,24
14,1.006227,0.019225,0.013805,0.003136,absolute_error,sqrt,50,"{'criterion': 'absolute_error', 'max_features'...",0.858924,0.797725,0.799562,0.817623,0.766215,0.808010,0.030360,14
15,1.946391,0.043357,0.022106,0.002324,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.861444,0.791321,0.807750,0.824142,0.769908,0.810913,0.030996,8
16,1.019864,0.037907,0.014853,0.002088,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.851265,0.795848,0.795227,0.818230,0.767849,0.805684,0.027830,15
17,1.916229,0.092165,0.033841,0.002294,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.860662,0.799511,0.809403,0.819252,0.774476,0.812661,0.028246,3
18,0.595323,0.007865,0.020258,0.009124,poisson,None,50,"{'criterion': 'poisson', 'max_features': None,...",0.860556,0.762912,0.809340,0.800945,0.767804,0.800311,0.035119,21
19,1.051358,0.047007,0.030971,0.008340,poisson,None,100,"{'criterion': 'poisson', 'max_features': None,...",0.864047,0.764039,0.813168,0.802943,0.767197,0.802279,0.036407,19
20,0.413125,0.011411,0.016453,0.005967,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.859854,0.780440,0.808957,0.822900,0.768400,0.808110,0.032371,13
21,0.832326,0.034985,0.030236,0.005561,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.867732,0.788338,0.799889,0.830454,0.773203,0.811923,0.033640,6
22,0.419422,0.013220,0.011974,0.002470,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.865088,0.790700,0.808355,0.823112,0.765318,0.810515,0.033397,9
23,0.619865,0.027219,0.022183,0.006089,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.858958,0.791598,0.801661,0.826621,0.771059,0.809980,0.030324,11