In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
indep=SC.fit_transform(indep)

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {'criterion':['squared_error','friedman_mse','absolute_error','poisson'],'max_features': [None,'sqrt','log2'],'n_estimators':[50,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose=3,n_jobs=-1)
regressor=grid.fit(indep,dep)
y_pred=regressor.predict(indep)
y_pred

Fitting 5 folds for each of 24 candidates, totalling 120 fits

array([17028.76591  ,  3474.4950088,  4724.9021766, ...,  2573.350171 ,
        2217.866378 , 28153.979672 ])

In [9]:
from sklearn.metrics import r2_score
r_score=r2_score(dep,y_pred)
r_score

0.9752644450310228

In [10]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'poisson', 'max_features': 'sqrt', 'n_estimators': 50}:

In [11]:
table=pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.330632,0.008413,0.012725,0.006278,squared_error,None,50,"{'criterion': 'squared_error', 'max_features':...",0.844311,0.771102,0.852750,0.819881,0.833601,0.824329,0.028795,22
1,0.662603,0.013599,0.021995,0.005159,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",0.850871,0.775502,0.858526,0.820123,0.841416,0.829288,0.029815,17
2,0.246395,0.009500,0.010302,0.003159,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.859905,0.780526,0.860913,0.823997,0.845967,0.834261,0.029993,6
3,0.496986,0.009340,0.019627,0.001969,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.858908,0.779970,0.863241,0.829002,0.841159,0.834456,0.029900,4
4,0.249026,0.003071,0.009696,0.004767,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.859640,0.776923,0.866680,0.825623,0.838384,0.833450,0.031847,10
5,0.501332,0.012085,0.021018,0.002344,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.855855,0.780062,0.862211,0.827708,0.841724,0.833512,0.029260,9
6,0.329879,0.010034,0.007428,0.004504,friedman_mse,None,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.849650,0.768135,0.859087,0.816888,0.840964,0.826945,0.032573,20
7,0.652192,0.008958,0.020761,0.002194,friedman_mse,None,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.850159,0.772272,0.858191,0.818030,0.839024,0.827535,0.030751,18
8,0.261594,0.005529,0.009888,0.004752,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.858817,0.780920,0.855788,0.832312,0.842220,0.834011,0.028208,7
9,0.505721,0.023420,0.018939,0.001904,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.860570,0.777685,0.862577,0.826574,0.844186,0.834318,0.031152,5
10,0.252342,0.005928,0.011919,0.004539,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.860920,0.779086,0.856569,0.824969,0.840862,0.832481,0.029552,12
11,0.721315,0.040409,0.036459,0.005153,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.856996,0.781035,0.861753,0.823949,0.839563,0.832659,0.029077,11
12,2.470019,0.040533,0.018404,0.002116,absolute_error,None,50,"{'criterion': 'absolute_error', 'max_features'...",0.833312,0.761103,0.849092,0.824953,0.834290,0.820550,0.030723,24
13,4.975797,0.053833,0.031910,0.002498,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",0.840167,0.767360,0.847940,0.822831,0.838375,0.823334,0.029149,23
14,1.487575,0.023591,0.017706,0.001367,absolute_error,sqrt,50,"{'criterion': 'absolute_error', 'max_features'...",0.856503,0.781783,0.852942,0.819330,0.845081,0.831128,0.027887,16
15,2.894444,0.041618,0.032107,0.001521,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.857234,0.785050,0.856905,0.829660,0.844049,0.834580,0.026753,3
16,1.471357,0.039204,0.016674,0.005985,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.853185,0.784118,0.852294,0.825707,0.842622,0.831585,0.025709,15
17,2.951867,0.056836,0.033868,0.002922,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.857569,0.780100,0.855065,0.826152,0.841646,0.832106,0.028308,13
18,0.656017,0.017122,0.019193,0.003616,poisson,None,50,"{'criterion': 'poisson', 'max_features': None,...",0.844670,0.767045,0.860609,0.821120,0.843655,0.827420,0.032703,19
19,1.314126,0.025269,0.033924,0.003673,poisson,None,100,"{'criterion': 'poisson', 'max_features': None,...",0.852298,0.765716,0.858634,0.820376,0.836377,0.826680,0.033250,21
20,0.504207,0.024160,0.019142,0.002410,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.855675,0.785912,0.864535,0.829930,0.843697,0.835950,0.027591,1
21,0.989675,0.016605,0.029367,0.004631,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.861709,0.783498,0.862255,0.825516,0.840753,0.834746,0.029091,2
22,0.493777,0.013951,0.018342,0.007870,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.857970,0.772523,0.861652,0.823317,0.845039,0.832100,0.032670,14
23,0.689436,0.029511,0.024435,0.006947,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.858668,0.777049,0.862018,0.829247,0.841756,0.833748,0.030722,8