In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('50_Startups.csv')

In [3]:
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [5]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [6]:
independent=dataset[['R&D Spend','Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dependent=dataset[['Profit']]

In [7]:
independent

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   165349.20       136897.80        471784.10              0               1
1   162597.70       151377.59        443898.53              0               0
2   153441.51       101145.55        407934.54              1               0
3   144372.41       118671.85        383199.62              0               1
4   142107.34        91391.77        366168.42              1               0
5   131876.90        99814.71        362861.36              0               1
6   134615.46       147198.87        127716.82              0               0
7   130298.13       145530.06        323876.68              1               0
8   120542.52       148718.95        311613.29              0               1
9   123334.88       108679.17        304981.62              0               0
10  101913.08       110594.11        229160.95              1               0
11  100671.96        91790.61        249744.55              0               0
12   93863.75       127320.38        249839.44              1               0
13   91992.39       135495.07        252664.93              0               0
14  119943.24       156547.42        256512.92              1               0
15  114523.61       122616.84        261776.23              0               1
16   78013.11       121597.55        264346.06              0               0
17   94657.16       145077.58        282574.31              0               1
18   91749.16       114175.79        294919.57              1               0
19   86419.70       153514.11             0.00              0               1
20   76253.86       113867.30        298664.47              0               0
21   78389.47       153773.43        299737.29              0               1
22   73994.56       122782.75        303319.26              1               0
23   67532.53       105751.03        304768.73              1               0
24   77044.01        99281.34        140574.81              0               1
25   64664.71       139553.16        137962.62              0               0
26   75328.87       144135.98        134050.07              1               0
27   72107.60       127864.55        353183.81              0               1
28   66051.52       182645.56        118148.20              1               0
29   65605.48       153032.06        107138.38              0               1
30   61994.48       115641.28         91131.24              1               0
31   61136.38       152701.92         88218.23              0               1
32   63408.86       129219.61         46085.25              0               0
33   55493.95       103057.49        214634.81              1               0
34   46426.07       157693.92        210797.67              0               0
35   46014.02        85047.44        205517.64              0               1
36   28663.76       127056.21        201126.82              1               0
37   44069.95        51283.14        197029.42              0               0
38   20229.59        65947.93        185265.10              0               1
39   38558.51        82982.09        174999.30              0               0
40   28754.33       118546.05        172795.67              0               0
41   27892.92        84710.77        164470.71              1               0
42   23640.93        96189.63        148001.11              0               0
43   15505.73       127382.30         35534.17              0               1
44   22177.74       154806.14         28334.72              0               0
45    1000.23       124153.04          1903.93              0               1
46    1315.46       115816.21        297114.46              1               0
47       0.00       135426.92             0.00              0               0
48     542.05        51743.15             0.00              0               1
49       0.00       116983.80         45173.06              0               0

In [8]:
dependent

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=42)
#Split the data into training and testing sets (70% train, 30% test).

In [10]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
X_train=SC.fit_transform(X_train)
X_test=SC.transform(X_test)

In [11]:
X_test

array([[ 0.40045135,  0.48698777,  0.22829319, -0.72231512, -0.6770032 ],
       [-0.73915001, -1.5753814 , -0.44533044, -0.72231512, -0.6770032 ],
       [-0.23932362, -0.2927403 , -1.17275011,  1.38443731, -0.6770032 ],
       [-1.5401674 ,  0.04154642, -1.9466526 , -0.72231512,  1.47709789],
       [ 0.45728375,  0.8633266 ,  0.48770865, -0.72231512,  1.47709789],
       [-1.54993915, -2.8022443 , -1.96316611, -0.72231512,  1.47709789],
       [ 0.04506316,  0.82634666, -0.80049873,  1.38443731, -0.6770032 ],
       [-0.18237477,  0.64636322, -0.76656369, -0.72231512, -0.6770032 ],
       [-0.20915869,  0.24052842, -1.56345116, -0.72231512, -0.6770032 ],
       [ 0.28160082,  1.19465877, -1.96316611, -0.72231512,  1.47709789],
       [ 0.44036245,  0.16593898,  0.20378663,  1.38443731, -0.6770032 ],
       [ 1.46926884, -1.24510373,  1.21275224,  1.38443731, -0.6770032 ],
       [-0.62160577, -2.82031051, -0.25425481, -0.72231512, -0.6770032 ],
       [ 1.00934906,  1.00633599,  0.73957479, -0.72231512,  1.47709789],
       [ 1.51757671, -0.17371917,  1.36047034, -0.72231512,  1.47709789]])

In [12]:
X_train

array([[ 1.30948713,  0.94663711, -0.85542942, -0.72231512, -0.6770032 ],
       [-0.96661844, -1.50749007, -0.53664892,  1.38443731, -0.6770032 ],
       [-1.53344439, -0.28587018,  0.61382091,  1.38443731, -0.6770032 ],
       [-1.56149962,  0.48431128, -1.96316611, -0.72231512, -0.6770032 ],
       [ 0.88098185, -0.01878555,  0.30731897, -0.72231512,  1.47709789],
       [ 1.06890261, -0.56616681,  0.68205579, -0.72231512, -0.6770032 ],
       [ 0.1023108 , -0.05881665,  0.32960808, -0.72231512, -0.6770032 ],
       [ 0.0816425 , -0.9352526 , -0.74390717, -0.72231512,  1.47709789],
       [-0.57135605,  1.35881459, -0.13483753, -0.72231512, -0.6770032 ],
       [-0.25762459,  1.16276121, -1.19801576, -0.72231512,  1.47709789],
       [ 1.96495539,  0.54207791,  2.12879731, -0.72231512,  1.47709789],
       [-1.0885079 ,  1.24540132, -1.71740828, -0.72231512, -0.6770032 ],
       [-0.02363789,  0.18731045,  1.10013177, -0.72231512,  1.47709789],
       [-0.37796249, -0.78694993, -0.10155655,  1.38443731, -0.6770032 ],
       [ 1.25108099, -0.91430529,  1.18406885, -0.72231512,  1.47709789],
       [-0.16231067,  1.17572697, -1.03391408, -0.72231512,  1.47709789],
       [ 0.58556331, -1.22943988,  0.20296362, -0.72231512, -0.6770032 ],
       [-0.95017849,  0.1555641 , -0.2187165 ,  1.38443731, -0.6770032 ],
       [ 1.90627327,  1.11075012,  1.88693513, -0.72231512, -0.6770032 ],
       [ 0.11033755,  1.20484317,  0.63656972, -0.72231512,  1.47709789],
       [ 1.71099629, -0.86203853,  1.57500573,  1.38443731, -0.6770032 ],
       [-1.23080398,  0.1683708 , -1.6549647 , -0.72231512,  1.47709789],
       [-0.58014397, -1.49426785, -0.18063324, -0.72231512,  1.47709789],
       [-0.12121186, -0.68116515,  0.68020932,  1.38443731, -0.6770032 ],
       [-0.94824687, -0.17865978, -0.46444337, -0.72231512, -0.6770032 ],
       [ 0.61203307, -0.49096039,  0.0244342 ,  1.38443731, -0.6770032 ],
       [ 0.01660591, -0.01226968,  0.66763751,  1.38443731, -0.6770032 ],
       [ 0.39526391, -0.35029524,  0.59478379,  1.38443731, -0.6770032 ],
       [-1.56149962, -0.24001482, -1.57136293, -0.72231512, -0.6770032 ],
       [ 0.06479072, -0.36241072,  0.62726474, -0.72231512, -0.6770032 ],
       [ 1.21741006,  0.88109708,  0.84593985,  1.38443731, -0.6770032 ],
       [-1.05730198, -1.05667492, -0.67949604, -0.72231512, -0.6770032 ],
       [ 0.99656803,  1.3137875 ,  0.26166827,  1.38443731, -0.6770032 ],
       [-0.15279783,  2.33875313, -0.93842171,  1.38443731, -0.6770032 ],
       [-1.13005672, -2.2443727 , -0.35629124, -0.72231512,  1.47709789]])

In [13]:
import pickle

In [14]:
filename="SVM_final.sav"
#pickle.dump(regressor,open(filename,"wb"))

In [15]:
loaded_model=pickle.load(open("SVM_final.sav",'rb'))

In [16]:
Preinput=SC.transform([[1234,345,4565,1,0]])

C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [17]:
Preinput

array([[-1.53518171, -4.82083019, -1.92357213,  1.38443731, -0.6770032 ]])

In [18]:
result=loaded_model.predict(Preinput)

In [19]:
result

array([48108.67840693])