In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
indep=SC.fit_transform(X_train)
X_test=SC.transform(X_test)

In [9]:
X_train

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]

In [10]:
X_test

array([[ 0.89459283, -0.08863026, -0.06746417,  1.02378711, -0.50466988],
       [ 0.53757957, -0.22180837, -0.06746417, -0.97676557, -0.50466988],
       [ 0.60898222,  1.57449152,  0.76341038,  1.02378711,  1.98149332],
       ...,
       [ 1.10880078,  1.20785059, -0.89833872,  1.02378711, -0.50466988],
       [ 1.75142463,  1.34905148, -0.06746417,  1.02378711, -0.50466988],
       [ 1.60861933, -0.92299913, -0.89833872, -0.97676557, -0.50466988]])

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae','friedman_mse'],
'max_features': ['auto','sqrt','log2'],
'splitter':['best','random']}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose=3,n_jobs=-1)
regressor=grid.fit(X_train,y_train)
y_pred=regressor.predict(X_test)
y_pred

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning:
70 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'squared_error', 'absolute_error', 'poisson'}. Got 'mse' instead.

--------------------------------------------------------------------------------
23 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'absolute_error', 'poisson', 'squared_error'}. Got 'mse' instead.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'absolute_error', 'squared_error', 'poisson', 'friedman_mse'}. Got 'mse' instead.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'squared_error', 'absolute_error', 'friedman_mse', 'poisson'}. Got 'mse' instead.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'poisson', 'squared_error', 'absolute_error', 'friedman_mse'}. Got 'mse' instead.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'poisson', 'friedman_mse', 'absolute_error', 'squared_error'}. Got 'mse' instead.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'squared_error', 'poisson', 'friedman_mse', 'absolute_error'}. Got 'mse' instead.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'squared_error', 'absolute_error'}. Got 'mse' instead.

--------------------------------------------------------------------------------
16 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'absolute_error', 'poisson', 'squared_error'}. Got 'mae' instead.

--------------------------------------------------------------------------------
13 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'squared_error', 'absolute_error', 'friedman_mse', 'poisson'}. Got 'mae' instead.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'absolute_error', 'squared_error', 'poisson', 'friedman_mse'}. Got 'mae' instead.

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.58273461 0.53221705 0.66518013 0.54036557]
  warnings.warn(
C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([ 1694.7964 ,  2196.4732 , 13747.87235,  1694.7964 ,  2196.4732 ,
        1694.7964 ,  2196.4732 ,  2201.0971 ,  2201.0971 ,  1711.0268 ,
        2201.0971 ,  2201.0971 ,  2196.4732 ,  2196.4732 , 13747.87235,
        2201.0971 ,  1694.7964 ,  1694.7964 ,  1711.0268 , 13747.87235,
       13747.87235,  2201.0971 ,  2196.4732 , 13747.87235,  1694.7964 ,
        1694.7964 ,  2196.4732 ,  2201.0971 ,  2196.4732 ,  1711.0268 ,
        2201.0971 , 13747.87235,  1694.7964 ,  1694.7964 , 13747.87235,
        2196.4732 ,  1711.0268 , 13747.87235, 13747.87235,  2196.4732 ,
        2196.4732 ,  1694.7964 , 13747.87235, 13747.87235, 13747.87235,
        2201.0971 ,  2201.0971 ,  1694.7964 ,  2196.4732 ,  2196.4732 ,
        2196.4732 ,  2201.0971 , 13747.87235, 12829.4551 ,  2196.4732 ,
        1694.7964 ,  1694.7964 ,  1694.7964 ,  4005.4225 ,  1694.7964 ,
        1694.7964 , 12829.4551 ,  1711.0268 ,  1711.0268 ,  1711.0268 ,
        2196.4732 , 13747.87235, 12829.4551 ,  2201.0971 ,  1711.0268 ,
        2196.4732 ,  1694.7964 , 13747.87235,  2196.4732 ,  2196.4732 ,
        2196.4732 ,  1694.7964 ,  1711.0268 , 13747.87235, 13747.87235,
        2196.4732 , 13747.87235,  1694.7964 ,  1694.7964 , 13747.87235,
       13747.87235,  2196.4732 ,  1694.7964 ,  1694.7964 , 13747.87235,
        2201.0971 ,  1694.7964 ,  2196.4732 ,  2201.0971 ,  1694.7964 ,
        2196.4732 , 13747.87235, 13747.87235,  2201.0971 ,  1694.7964 ,
        1694.7964 ,  1694.7964 ,  2201.0971 , 13747.87235, 12829.4551 ,
        2196.4732 ,  1694.7964 ,  2196.4732 ,  1694.7964 , 13747.87235,
        2201.0971 ,  1711.0268 ,  2196.4732 , 13747.87235, 13747.87235,
        1711.0268 ,  1694.7964 ,  1694.7964 ,  1694.7964 ,  1711.0268 ,
       12829.4551 ,  2196.4732 ,  2196.4732 ,  1711.0268 ,  2196.4732 ,
        2201.0971 , 13747.87235, 13747.87235, 13747.87235,  1694.7964 ,
        2201.0971 ,  1694.7964 ,  2196.4732 ,  1694.7964 , 13747.87235,
       13747.87235, 13747.87235,  2201.0971 , 13747.87235,  1694.7964 ,
        2196.4732 ,  1694.7964 ,  1711.0268 ,  1694.7964 ,  1694.7964 ,
        2196.4732 ,  2196.4732 ,  2201.0971 ,  1694.7964 ,  1694.7964 ,
        2196.4732 , 13747.87235,  1694.7964 ,  1694.7964 ,  2196.4732 ,
        2196.4732 ,  1694.7964 ,  1694.7964 ,  2201.0971 ,  2201.0971 ,
        1711.0268 ,  1694.7964 ,  2196.4732 ,  1694.7964 ,  2196.4732 ,
        1711.0268 , 13747.87235,  2201.0971 ,  1694.7964 ,  2196.4732 ,
        1711.0268 ,  1711.0268 ,  2201.0971 ,  1694.7964 ,  1711.0268 ,
        1711.0268 ,  1711.0268 ,  1694.7964 , 12829.4551 ,  1694.7964 ,
        2201.0971 ,  1711.0268 ,  1694.7964 ,  1694.7964 ,  1711.0268 ,
       13747.87235,  1694.7964 ,  2196.4732 ,  2196.4732 ,  2201.0971 ,
       13747.87235,  2201.0971 ,  2196.4732 , 13747.87235,  1694.7964 ,
        1694.7964 ,  1711.0268 ,  2201.0971 ,  1711.0268 ,  1694.7964 ,
        2196.4732 , 13747.87235,  2201.0971 , 12829.4551 ,  1711.0268 ,
       13747.87235,  1711.0268 ,  1694.7964 ,  2201.0971 ,  1694.7964 ,
        1694.7964 ,  2196.4732 ,  2201.0971 ,  2196.4732 ,  1694.7964 ,
        1694.7964 ,  1711.0268 ,  2196.4732 ,  2201.0971 ,  2201.0971 ,
        2201.0971 ,  2201.0971 ,  2196.4732 ,  2196.4732 ,  2196.4732 ,
        1694.7964 ,  2201.0971 ,  2196.4732 ,  1711.0268 ,  1694.7964 ,
        1694.7964 ,  1694.7964 ,  2196.4732 ,  2201.0971 ,  2196.4732 ,
        1711.0268 ,  2196.4732 , 13747.87235,  1694.7964 ,  2201.0971 ,
        2196.4732 , 12829.4551 ,  2201.0971 ,  2196.4732 ,  1711.0268 ,
        1694.7964 ,  1711.0268 ,  2196.4732 ,  2196.4732 ,  1694.7964 ,
       13747.87235, 13747.87235,  2201.0971 ,  2196.4732 ,  2196.4732 ,
        1694.7964 ,  1694.7964 ,  2196.4732 ,  1711.0268 ,  2196.4732 ,
        1711.0268 , 13747.87235, 13747.87235,  2201.0971 ,  1694.7964 ,
        1694.7964 , 12829.4551 ,  1711.0268 , 12829.4551 ,  1694.7964 ,
       13747.87235,  1711.0268 ,  2196.4732 ,  2201.0971 , 13747.87235,
        2196.4732 ,  1694.7964 ,  4005.4225 ,  1694.7964 ,  2196.4732 ,
        2196.4732 ,  1694.7964 ,  1694.7964 ,  2196.4732 ,  1694.7964 ,
        1711.0268 ,  4005.4225 , 13747.87235,  1694.7964 ,  1694.7964 ,
        1711.0268 , 13747.87235,  1694.7964 ,  2196.4732 ,  2201.0971 ,
        2196.4732 , 13747.87235,  2196.4732 ,  1694.7964 ,  1694.7964 ,
        1694.7964 ,  1711.0268 , 13747.87235, 13747.87235,  2196.4732 ,
        1694.7964 ,  2196.4732 ,  1711.0268 ,  1694.7964 , 13747.87235,
       12829.4551 ,  2201.0971 , 13747.87235,  2196.4732 ,  1694.7964 ,
        1694.7964 ,  2196.4732 ,  1711.0268 ,  1694.7964 , 13747.87235,
        2201.0971 ,  2196.4732 ,  2196.4732 ,  2196.4732 ,  2196.4732 ,
        2196.4732 , 13747.87235, 13747.87235,  1694.7964 , 13747.87235,
        2201.0971 ,  1711.0268 ,  1694.7964 ,  1711.0268 , 13747.87235,
        2196.4732 ,  2196.4732 ,  1694.7964 , 13747.87235,  2196.4732 ,
       12829.4551 ,  2196.4732 ,  1694.7964 , 13747.87235,  2201.0971 ,
        2196.4732 , 12829.4551 ,  1694.7964 ,  1711.0268 ,  1711.0268 ,
        4005.4225 ,  2196.4732 ,  1711.0268 ,  1711.0268 , 13747.87235,
        2196.4732 , 13747.87235, 13747.87235,  1694.7964 ,  4005.4225 ,
        1694.7964 ,  2196.4732 ,  2201.0971 ,  1694.7964 , 13747.87235,
        1694.7964 ,  2196.4732 ,  1694.7964 ,  2196.4732 ,  2196.4732 ,
        1694.7964 ,  1694.7964 ,  1694.7964 , 13747.87235,  1711.0268 ,
        2196.4732 , 13747.87235,  1694.7964 , 13747.87235,  1694.7964 ,
        1694.7964 ,  1694.7964 ,  2196.4732 ,  2201.0971 ,  1694.7964 ,
        2196.4732 ,  2196.4732 ,  2201.0971 ,  1694.7964 ,  2201.0971 ,
        2196.4732 , 13747.87235,  1694.7964 ,  2196.4732 ,  2196.4732 ,
        2196.4732 ,  1694.7964 ,  1694.7964 , 12829.4551 ,  1694.7964 ,
        1694.7964 ,  2196.4732 ])

In [12]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

-0.024189087545340993