In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0         True
1    15810944   35            20000          0         True
2    15668575   26            43000          0        False
3    15603246   27            57000          0        False
4    15804002   19            76000          0         True
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1        False
396  15706071   51            23000          1         True
397  15654296   50            20000          1        False
398  15755018   36            33000          0         True
399  15594041   49            36000          1        False

[400 rows x 5 columns]

In [6]:
dataset=dataset.drop("User ID",axis=1)

In [7]:
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0         True
1     35            20000          0         True
2     26            43000          0        False
3     27            57000          0        False
4     19            76000          0         True
..   ...              ...        ...          ...
395   46            41000          1        False
396   51            23000          1         True
397   50            20000          1        False
398   36            33000          0         True
399   49            36000          1        False

[400 rows x 4 columns]

In [8]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [9]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset["Purchased"]

In [10]:
indep.shape

(400, 3)

In [11]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
param_grid = {
    'n_neighbors': [ 5, 10,50,100],  
    'weights': ['uniform', 'distance',None],  
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'] } 
grid = GridSearchCV(KNeighborsClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(indep, dep)
print("Best parameters found: ", grid.best_params_)
y_pred = grid.predict(indep)
print("Predictions: ", y_pred)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
Best parameters found:  {'algorithm': 'auto', 'n_neighbors': 5, 'weights': 'distance'}
Predictions:  [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]

In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(dep, y_pred)
print(cm)

[[257   0]
 [  1 142]]

In [14]:
from sklearn.metrics import classification_report
clf_report = classification_report(dep, y_pred)

In [15]:
print(clf_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       257
           1       1.00      0.99      1.00       143

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

In [16]:
print(cm)

[[257   0]
 [  1 142]]

In [17]:
grid.predict([[27,57000,0]])

C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [18]:
re=grid.cv_results_

In [19]:
table=pd.DataFrame.from_dict(re)

In [20]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015635,0.012014,0.054357,0.014152,auto,5,uniform,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.8125,0.8625,0.7250,0.7625,0.6750,0.7675,0.065479,27
1,0.008031,0.001269,0.007602,0.001327,auto,5,distance,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.8375,0.8500,0.7750,0.7250,0.7125,0.7800,0.056236,1
2,0.014139,0.014512,0.032563,0.011196,auto,5,None,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.8125,0.8625,0.7250,0.7625,0.6750,0.7675,0.065479,27
3,0.006739,0.000881,0.025458,0.003960,auto,10,uniform,"{'algorithm': 'auto', 'n_neighbors': 10, 'weig...",0.8000,0.8375,0.7000,0.7750,0.6375,0.7500,0.072024,33
4,0.008039,0.000901,0.011331,0.005732,auto,10,distance,"{'algorithm': 'auto', 'n_neighbors': 10, 'weig...",0.8375,0.8375,0.7875,0.7250,0.7125,0.7800,0.053385,1
5,0.007425,0.001077,0.032182,0.014491,auto,10,None,"{'algorithm': 'auto', 'n_neighbors': 10, 'weig...",0.8000,0.8375,0.7000,0.7750,0.6375,0.7500,0.072024,33
6,0.006403,0.000857,0.029079,0.013905,auto,50,uniform,"{'algorithm': 'auto', 'n_neighbors': 50, 'weig...",0.8250,0.8375,0.6875,0.8500,0.6375,0.7675,0.087536,19
7,0.009915,0.005841,0.023281,0.029067,auto,50,distance,"{'algorithm': 'auto', 'n_neighbors': 50, 'weig...",0.8375,0.8375,0.7750,0.7250,0.7125,0.7775,0.053268,9
8,0.007513,0.002079,0.043583,0.021272,auto,50,None,"{'algorithm': 'auto', 'n_neighbors': 50, 'weig...",0.8250,0.8375,0.6875,0.8500,0.6375,0.7675,0.087536,19
9,0.007132,0.000963,0.034837,0.010754,auto,100,uniform,"{'algorithm': 'auto', 'n_neighbors': 100, 'wei...",0.7875,0.8250,0.7250,0.7500,0.6250,0.7425,0.067823,41
10,0.007329,0.000876,0.011750,0.003057,auto,100,distance,"{'algorithm': 'auto', 'n_neighbors': 100, 'wei...",0.8500,0.8375,0.7625,0.7250,0.7125,0.7775,0.056679,9
11,0.006917,0.001083,0.034344,0.014902,auto,100,None,"{'algorithm': 'auto', 'n_neighbors': 100, 'wei...",0.7875,0.8250,0.7250,0.7500,0.6250,0.7425,0.067823,41
12,0.009624,0.003068,0.036959,0.012339,ball_tree,5,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 5, '...",0.8125,0.8625,0.7250,0.7625,0.6750,0.7675,0.065479,27
13,0.006641,0.000599,0.007137,0.000920,ball_tree,5,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 5, '...",0.8375,0.8500,0.7750,0.7250,0.7125,0.7800,0.056236,1
14,0.006230,0.000415,0.026257,0.011946,ball_tree,5,None,"{'algorithm': 'ball_tree', 'n_neighbors': 5, '...",0.8125,0.8625,0.7250,0.7625,0.6750,0.7675,0.065479,27
15,0.010951,0.006937,0.044355,0.026107,ball_tree,10,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 10, ...",0.8000,0.8375,0.7000,0.7750,0.6375,0.7500,0.072024,33
16,0.007125,0.001564,0.008731,0.003005,ball_tree,10,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 10, ...",0.8375,0.8375,0.7875,0.7250,0.7125,0.7800,0.053385,1
17,0.006718,0.000611,0.026411,0.011984,ball_tree,10,None,"{'algorithm': 'ball_tree', 'n_neighbors': 10, ...",0.8000,0.8375,0.7000,0.7750,0.6375,0.7500,0.072024,33
18,0.006505,0.000558,0.021539,0.001393,ball_tree,50,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 50, ...",0.8250,0.8375,0.6875,0.8500,0.6375,0.7675,0.087536,19
19,0.007128,0.000931,0.014529,0.012295,ball_tree,50,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 50, ...",0.8375,0.8375,0.7750,0.7250,0.7125,0.7775,0.053268,9
20,0.007134,0.001696,0.033202,0.008363,ball_tree,50,None,"{'algorithm': 'ball_tree', 'n_neighbors': 50, ...",0.8250,0.8375,0.6875,0.8500,0.6375,0.7675,0.087536,19
21,0.008622,0.001847,0.037544,0.009435,ball_tree,100,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 100,...",0.7875,0.8250,0.7250,0.7500,0.6250,0.7425,0.067823,41
22,0.013650,0.005072,0.015437,0.004908,ball_tree,100,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 100,...",0.8500,0.8375,0.7625,0.7250,0.7125,0.7775,0.056679,9
23,0.008425,0.001246,0.041030,0.015599,ball_tree,100,None,"{'algorithm': 'ball_tree', 'n_neighbors': 100,...",0.7875,0.8250,0.7250,0.7500,0.6250,0.7425,0.067823,41
24,0.010634,0.005820,0.031118,0.006027,kd_tree,5,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 5, 'we...",0.8125,0.8625,0.7250,0.7625,0.6750,0.7675,0.065479,27
25,0.006928,0.000659,0.007313,0.000248,kd_tree,5,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 5, 'we...",0.8375,0.8500,0.7750,0.7250,0.7125,0.7800,0.056236,1
26,0.007621,0.001250,0.034225,0.010309,kd_tree,5,None,"{'algorithm': 'kd_tree', 'n_neighbors': 5, 'we...",0.8125,0.8625,0.7250,0.7625,0.6750,0.7675,0.065479,27
27,0.007232,0.001286,0.022046,0.002106,kd_tree,10,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 10, 'w...",0.8000,0.8375,0.7000,0.7750,0.6375,0.7500,0.072024,33
28,0.007557,0.000922,0.007917,0.001236,kd_tree,10,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 10, 'w...",0.8375,0.8375,0.7875,0.7250,0.7125,0.7800,0.053385,1
29,0.008739,0.001541,0.044562,0.023587,kd_tree,10,None,"{'algorithm': 'kd_tree', 'n_neighbors': 10, 'w...",0.8000,0.8375,0.7000,0.7750,0.6375,0.7500,0.072024,33
30,0.007121,0.001163,0.025922,0.003726,kd_tree,50,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 50, 'w...",0.8250,0.8375,0.6875,0.8500,0.6375,0.7675,0.087536,19
31,0.006926,0.000567,0.008049,0.001608,kd_tree,50,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 50, 'w...",0.8375,0.8375,0.7750,0.7250,0.7125,0.7775,0.053268,9
32,0.007519,0.000721,0.036717,0.010873,kd_tree,50,None,"{'algorithm': 'kd_tree', 'n_neighbors': 50, 'w...",0.8250,0.8375,0.6875,0.8500,0.6375,0.7675,0.087536,19
33,0.007927,0.000738,0.030179,0.011887,kd_tree,100,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 100, '...",0.7875,0.8250,0.7250,0.7500,0.6250,0.7425,0.067823,41
34,0.006303,0.000387,0.011024,0.002558,kd_tree,100,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 100, '...",0.8500,0.8375,0.7625,0.7250,0.7125,0.7775,0.056679,9
35,0.006619,0.000734,0.035705,0.014889,kd_tree,100,None,"{'algorithm': 'kd_tree', 'n_neighbors': 100, '...",0.7875,0.8250,0.7250,0.7500,0.6250,0.7425,0.067823,41
36,0.005801,0.000746,0.497784,0.256470,brute,5,uniform,"{'algorithm': 'brute', 'n_neighbors': 5, 'weig...",0.8125,0.8625,0.7250,0.7750,0.6750,0.7700,0.065479,17
37,0.006616,0.001477,0.292952,0.262879,brute,5,distance,"{'algorithm': 'brute', 'n_neighbors': 5, 'weig...",0.8375,0.8500,0.7750,0.7250,0.7125,0.7800,0.056236,1
38,0.006920,0.001333,0.044319,0.018010,brute,5,None,"{'algorithm': 'brute', 'n_neighbors': 5, 'weig...",0.8125,0.8625,0.7250,0.7750,0.6750,0.7700,0.065479,17
39,0.006022,0.001160,0.032852,0.011854,brute,10,uniform,"{'algorithm': 'brute', 'n_neighbors': 10, 'wei...",0.8000,0.8375,0.7000,0.7750,0.6375,0.7500,0.072024,33
40,0.007244,0.002459,0.009032,0.000714,brute,10,distance,"{'algorithm': 'brute', 'n_neighbors': 10, 'wei...",0.8375,0.8375,0.7875,0.7250,0.7125,0.7800,0.053385,1
41,0.007614,0.000862,0.065356,0.023004,brute,10,None,"{'algorithm': 'brute', 'n_neighbors': 10, 'wei...",0.8000,0.8375,0.7000,0.7750,0.6375,0.7500,0.072024,33
42,0.006216,0.000803,0.033085,0.014070,brute,50,uniform,"{'algorithm': 'brute', 'n_neighbors': 50, 'wei...",0.8250,0.8375,0.6875,0.8500,0.6375,0.7675,0.087536,19
43,0.012130,0.012757,0.008812,0.000523,brute,50,distance,"{'algorithm': 'brute', 'n_neighbors': 50, 'wei...",0.8375,0.8375,0.7750,0.7250,0.7125,0.7775,0.053268,9
44,0.005920,0.000749,0.027693,0.007075,brute,50,None,"{'algorithm': 'brute', 'n_neighbors': 50, 'wei...",0.8250,0.8375,0.6875,0.8500,0.6375,0.7675,0.087536,19
45,0.006532,0.001355,0.026169,0.003936,brute,100,uniform,"{'algorithm': 'brute', 'n_neighbors': 100, 'we...",0.7875,0.8250,0.7250,0.7500,0.6250,0.7425,0.067823,41
46,0.007335,0.001171,0.018943,0.012883,brute,100,distance,"{'algorithm': 'brute', 'n_neighbors': 100, 'we...",0.8500,0.8375,0.7625,0.7250,0.7125,0.7775,0.056679,9
47,0.006123,0.000368,0.035641,0.011081,brute,100,None,"{'algorithm': 'brute', 'n_neighbors': 100, 'we...",0.7875,0.8250,0.7250,0.7500,0.6250,0.7425,0.067823,41